# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6123fc4ee11806de9dfe6e5e164a21e8a75775f6b82caee36ea9458fb17449a4223f0c153204b1f0605bfa0924917762a482ab7bcc4e263a974b04a24d4ece2

test:
  secret_key_base: 98cfeb5938068134e87b671f6001dca9b62e18b590f9b07570c09fd26d66261fa3248c1137ffb7089f41484a94ba2c9ece7d5cb385fc19432089921642c60abb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
